CREATE TABLE VITALS (
  vitals_id INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  oxigen INTEGER UNSIGNED  NOT NULL  ,
  heart_rate INTEGER UNSIGNED  NOT NULL  ,
  temperature FLOAT  NOT NULL    ,
PRIMARY KEY(vitals_id));




